name: devops-project
services:
  app:
    container_name: go-app
    build:
      context: .
      dockerfile: ./user/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=devops_password_one_hundred

  redis:
    container_name: redis
    command: redis-server --requirepass devops_password_one_hundred
    image: redis:alpine
    ports:
      - 6379:6379