name: devops-project
services:
  app:
    container_name: go-app
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis:
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    image: redis:alpine
    ports:
      - 6379:6379