apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-project
  name: app-v1
  labels:
    io.kompose.service: app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
      version: v1
  template:
    metadata:
      labels:
        io.kompose.service: app
        version: v1
    spec:
      containers:
        - name: go-app
          image: maximehrt/devops-project-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              value: devops_password_one_hundred
            - name: REDIS_PORT
              value: "6379"
      restartPolicy: Always