apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: devops-project
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000  # Optional: change this if you want to use a different port to access Grafana
  selector:
    app: grafana
