apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-project
  name: app-v1
  labels:
    app: my-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              value: devops_password_one_hundred
            - name: REDIS_PORT
              value: "6379"
          image: maximehrt/devops-project-app:latest
          name: go-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              hostPort: 8081
              protocol: TCP
          resources: { }
      restartPolicy: Always
status: { }