### Get all Contacts
GET http://localhost:8080/contacts

### Get Contact by ID
GET http://localhost:8080/contacts/{id}

### Get Contact by Email
GET http://localhost:8080/contacts/user_email/{email}

### Create Contact
POST http://localhost:8080/contacts
content-type: application/json

{
  "name": "{NAME}",
  "email": "{EMAIL}",
  "phone": "{PHONE_NUMBER}"
}

### Update Contact
PUT http://localhost:8080/contacts/{id}
content-type: application/json

{
  "name": "{NAME}",
  "email": "{EMAIL}",
  "phone": "{PHONE_NUMBER}"
}

### Delete Contact
DELETE http://localhost:8080/contacts/id/{id}

### Delete Contact Mail
DELETE http://localhost:8080/contacts/email/{email}
