name: Go

on:
  push:
    branches:
      - main
      - Maxime
      - Maxence


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Download dependencies
        run: go mod download
        working-directory: user

      - name: Run tests
        run: go test -v ./...
        working-directory: user