### Get all Contacts
GET http://localhost:8080/contacts

### Get Contact by ID
GET http://localhost:8080/contacts/1701159646304553000

### Create Contact
POST http://localhost:8080/contacts
content-type: application/json

{
  "name": "Jordan",
  "email": "test@jordan.com",
  "phone": "1234567890"
}

### Update Contact
PUT http://localhost:8080/contacts/1701159646304553000
content-type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "phone": "1234567890"
}

### Delete Contact
DELETE http://localhost:8080/contacts/1701160229253841000
